#include "script_component.hpp"

class CfgPatches 
{
    class ADDON 
    {
        name = COMPONENT_NAME;
        units[] = {
            // base vehicles
            QGVAR(Vehicle_Car_Base),
            QGVAR(Vehicle_APC_Base),
            QGVAR(Vehicle_Tank_Base),
            QGVAR(Vehicle_Ship_Base),
            QGVAR(Vehicle_Heli_Base),
            QGVAR(Vehicle_Plane_Base),
            QGVAR(Vehicle_StaticWeapon_Base),
            QGVAR(Vehicle_StaticMortar_Base),

            // rebel units
            QGVAR(Rebels_Base),
            QGVAR(Rebels_Rifleman),
            QGVAR(Rebels_SquadLeader),
            QGVAR(Rebels_staticCrew),
            QGVAR(Rebels_Medic),
            QGVAR(Rebels_Engineer),
            QGVAR(Rebels_ExplosivesExpert),
            QGVAR(Rebels_Grenadier),
            QGVAR(Rebels_LAT),
            QGVAR(Rebels_AT),
            QGVAR(Rebels_AA),
            QGVAR(Rebels_MachineGunner),
            QGVAR(Rebels_Marksman),
            QGVAR(Rebels_Sniper),
            QGVAR(Rebels_Unarmed),

            // rebel vehicles
            QGVAR(Rebels_Vehicle_Basic),
            QGVAR(Rebels_Vehicle_LightUnarmed),
            QGVAR(Rebels_Vehicle_LightArmed),
            QGVAR(Rebels_Vehicle_Truck),
            QGVAR(Rebels_Vehicle_AT),
            QGVAR(Rebels_Vehicle_AA),
            QGVAR(Rebels_Vehicle_CivCar),
            QGVAR(Rebels_Vehicle_CivTruck),
            QGVAR(Rebels_Vehicle_Boat),
            QGVAR(Rebels_Vehicle_CivBoat),
            QGVAR(Rebels_Vehicle_CivHeli),
            QGVAR(Rebels_Vehicle_Plane),
            QGVAR(Rebels_Vehicle_CivPlane),
            QGVAR(Rebels_Vehicle_StaticMG),
            QGVAR(Rebels_Vehicle_StaticAT),
            QGVAR(Rebels_Vehicle_StaticAA),
            QGVAR(Rebels_Vehicle_Mortar),

            // occupant units
            QGVAR(Occupants_Base),
            QGVAR(Occupants_Militia_Rifleman),
            QGVAR(Occupants_Militia_SquadLeader),
            QGVAR(Occupants_Militia_staticCrew),
            QGVAR(Occupants_Militia_Medic),
            QGVAR(Occupants_Militia_Engineer),
            QGVAR(Occupants_Militia_ExplosivesExpert),
            QGVAR(Occupants_Militia_Grenadier),
            QGVAR(Occupants_Militia_LAT),
            QGVAR(Occupants_Militia_AT),
            QGVAR(Occupants_Militia_AA),
            QGVAR(Occupants_Militia_MachineGunner),
            QGVAR(Occupants_Militia_Marksman),
            QGVAR(Occupants_Militia_Sniper),
            QGVAR(Occupants_Militia_PatrolSniper),
            QGVAR(Occupants_Militia_PatrolSpotter),
            QGVAR(Occupants_Military_Rifleman),
            QGVAR(Occupants_Military_SquadLeader),
            QGVAR(Occupants_Military_staticCrew),
            QGVAR(Occupants_Military_Medic),
            QGVAR(Occupants_Military_Engineer),
            QGVAR(Occupants_Military_ExplosivesExpert),
            QGVAR(Occupants_Military_Grenadier),
            QGVAR(Occupants_Military_LAT),
            QGVAR(Occupants_Military_AT),
            QGVAR(Occupants_Military_AA),
            QGVAR(Occupants_Military_MachineGunner),
            QGVAR(Occupants_Military_Marksman),
            QGVAR(Occupants_Military_Sniper),
            QGVAR(Occupants_Military_PatrolSniper),
            QGVAR(Occupants_Military_PatrolSpotter),
            QGVAR(Occupants_Elite_Rifleman),
            QGVAR(Occupants_Elite_SquadLeader),
            QGVAR(Occupants_Elite_staticCrew),
            QGVAR(Occupants_Elite_Medic),
            QGVAR(Occupants_Elite_Engineer),
            QGVAR(Occupants_Elite_ExplosivesExpert),
            QGVAR(Occupants_Elite_Grenadier),
            QGVAR(Occupants_Elite_LAT),
            QGVAR(Occupants_Elite_AT),
            QGVAR(Occupants_Elite_AA),
            QGVAR(Occupants_Elite_MachineGunner),
            QGVAR(Occupants_Elite_Marksman),
            QGVAR(Occupants_Elite_Sniper),
            QGVAR(Occupants_SpecialForces_Rifleman),
            QGVAR(Occupants_SpecialForces_SquadLeader),
            QGVAR(Occupants_SpecialForces_staticCrew),
            QGVAR(Occupants_SpecialForces_Medic),
            QGVAR(Occupants_SpecialForces_Engineer),
            QGVAR(Occupants_SpecialForces_ExplosivesExpert),
            QGVAR(Occupants_SpecialForces_Grenadier),
            QGVAR(Occupants_SpecialForces_LAT),
            QGVAR(Occupants_SpecialForces_AT),
            QGVAR(Occupants_SpecialForces_AA),
            QGVAR(Occupants_SpecialForces_MachineGunner),
            QGVAR(Occupants_SpecialForces_Marksman),
            QGVAR(Occupants_SpecialForces_Sniper),
            QGVAR(Occupants_SpecialForces_PatrolSniper),
            QGVAR(Occupants_SpecialForces_PatrolSpotter),
            QGVAR(Occupants_Police_Standard),
            QGVAR(Occupants_Police_SquadLeader),
            QGVAR(Occupants_Other_Crew),
            QGVAR(Occupants_Other_Pilot),
            QGVAR(Occupants_Other_Official),
            QGVAR(Occupants_Other_Traitor),
            QGVAR(Occupants_Other_Unarmed),

            // occupant vehicles
            QGVAR(Occupants_Vehicle_Basic),
            QGVAR(Occupants_Vehicle_LightUnarmed),
            QGVAR(Occupants_Vehicle_MilitiaCar),
            QGVAR(Occupants_Vehicle_Police),
            QGVAR(Occupants_Vehicle_LightArmed),
            QGVAR(Occupants_Vehicle_MilitiaLightArmed),
            QGVAR(Occupants_Vehicle_Truck),
            QGVAR(Occupants_Vehicle_CargoTruck),
            QGVAR(Occupants_Vehicle_AmmoTruck),
            QGVAR(Occupants_Vehicle_RepairTruck),
            QGVAR(Occupants_Vehicle_FuelTruck),
            QGVAR(Occupants_Vehicle_MilitiaTruck),
            QGVAR(Occupants_Vehicle_Medical),
            QGVAR(Occupants_Vehicle_AA),
            QGVAR(Occupants_Vehicle_APC),
            QGVAR(Occupants_Vehicle_LightAPC),
            QGVAR(Occupants_Vehicle_MilitiaAPC),
            QGVAR(Occupants_Vehicle_IFV),
            QGVAR(Occupants_Vehicle_Tank),
            QGVAR(Occupants_Vehicle_LightTank),
            QGVAR(Occupants_Vehicle_TransportBoat),
            QGVAR(Occupants_Vehicle_GunBoat),
            QGVAR(Occupants_Vehicle_LightHeli),
            QGVAR(Occupants_Vehicle_LightAttackHeli),
            QGVAR(Occupants_Vehicle_AttackHeli),
            QGVAR(Occupants_Vehicle_TransportHeli),
            QGVAR(Occupants_Vehicle_CASPlane),
            QGVAR(Occupants_Vehicle_AAPlane),
            QGVAR(Occupants_Vehicle_TransportPlane),
            QGVAR(Occupants_Vehicle_StaticMG),
            QGVAR(Occupants_Vehicle_StaticAT),
            QGVAR(Occupants_Vehicle_StaticAA),
            QGVAR(Occupants_Vehicle_Mortar),

            // invader units
            QGVAR(Invaders_Base),
            QGVAR(Invaders_Militia_Rifleman),
            QGVAR(Invaders_Militia_SquadLeader),
            QGVAR(Invaders_Militia_staticCrew),
            QGVAR(Invaders_Militia_Medic),
            QGVAR(Invaders_Militia_Engineer),
            QGVAR(Invaders_Militia_ExplosivesExpert),
            QGVAR(Invaders_Militia_Grenadier),
            QGVAR(Invaders_Militia_LAT),
            QGVAR(Invaders_Militia_AT),
            QGVAR(Invaders_Militia_AA),
            QGVAR(Invaders_Militia_MachineGunner),
            QGVAR(Invaders_Militia_Marksman),
            QGVAR(Invaders_Militia_Sniper),
            QGVAR(Invaders_Militia_PatrolSniper),
            QGVAR(Invaders_Militia_PatrolSpotter),
            QGVAR(Invaders_Military_Rifleman),
            QGVAR(Invaders_Military_SquadLeader),
            QGVAR(Invaders_Military_staticCrew),
            QGVAR(Invaders_Military_Medic),
            QGVAR(Invaders_Military_Engineer),
            QGVAR(Invaders_Military_ExplosivesExpert),
            QGVAR(Invaders_Military_Grenadier),
            QGVAR(Invaders_Military_LAT),
            QGVAR(Invaders_Military_AT),
            QGVAR(Invaders_Military_AA),
            QGVAR(Invaders_Military_MachineGunner),
            QGVAR(Invaders_Military_Marksman),
            QGVAR(Invaders_Military_Sniper),
            QGVAR(Invaders_Military_PatrolSniper),
            QGVAR(Invaders_Military_PatrolSpotter),
            QGVAR(Invaders_Elite_Rifleman),
            QGVAR(Invaders_Elite_SquadLeader),
            QGVAR(Invaders_Elite_staticCrew),
            QGVAR(Invaders_Elite_Medic),
            QGVAR(Invaders_Elite_Engineer),
            QGVAR(Invaders_Elite_ExplosivesExpert),
            QGVAR(Invaders_Elite_Grenadier),
            QGVAR(Invaders_Elite_LAT),
            QGVAR(Invaders_Elite_AT),
            QGVAR(Invaders_Elite_AA),
            QGVAR(Invaders_Elite_MachineGunner),
            QGVAR(Invaders_Elite_Marksman),
            QGVAR(Invaders_Elite_Sniper),
            QGVAR(Invaders_SpecialForces_Rifleman),
            QGVAR(Invaders_SpecialForces_SquadLeader),
            QGVAR(Invaders_SpecialForces_staticCrew),
            QGVAR(Invaders_SpecialForces_Medic),
            QGVAR(Invaders_SpecialForces_Engineer),
            QGVAR(Invaders_SpecialForces_ExplosivesExpert),
            QGVAR(Invaders_SpecialForces_Grenadier),
            QGVAR(Invaders_SpecialForces_LAT),
            QGVAR(Invaders_SpecialForces_AT),
            QGVAR(Invaders_SpecialForces_AA),
            QGVAR(Invaders_SpecialForces_MachineGunner),
            QGVAR(Invaders_SpecialForces_Marksman),
            QGVAR(Invaders_SpecialForces_Sniper),
            QGVAR(Invaders_SpecialForces_PatrolSniper),
            QGVAR(Invaders_SpecialForces_PatrolSpotter),
            QGVAR(Invaders_Police_Standard),
            QGVAR(Invaders_Police_SquadLeader),
            QGVAR(Invaders_Other_Crew),
            QGVAR(Invaders_Other_Pilot),
            QGVAR(Invaders_Other_Official),
            QGVAR(Invaders_Other_Traitor),
            QGVAR(Invaders_Other_Unarmed),

            // invader vehicles
            QGVAR(Invaders_Vehicle_Basic),
            QGVAR(Invaders_Vehicle_LightUnarmed),
            QGVAR(Invaders_Vehicle_MilitiaCar),
            QGVAR(Invaders_Vehicle_Police),
            QGVAR(Invaders_Vehicle_LightArmed),
            QGVAR(Invaders_Vehicle_MilitiaLightArmed),
            QGVAR(Invaders_Vehicle_Truck),
            QGVAR(Invaders_Vehicle_CargoTruck),
            QGVAR(Invaders_Vehicle_AmmoTruck),
            QGVAR(Invaders_Vehicle_RepairTruck),
            QGVAR(Invaders_Vehicle_FuelTruck),
            QGVAR(Invaders_Vehicle_MilitiaTruck),
            QGVAR(Invaders_Vehicle_Medical),
            QGVAR(Invaders_Vehicle_AA),
            QGVAR(Invaders_Vehicle_APC),
            QGVAR(Invaders_Vehicle_LightAPC),
            QGVAR(Invaders_Vehicle_MilitiaAPC),
            QGVAR(Invaders_Vehicle_IFV),
            QGVAR(Invaders_Vehicle_Tank),
            QGVAR(Invaders_Vehicle_LightTank),
            QGVAR(Invaders_Vehicle_TransportBoat),
            QGVAR(Invaders_Vehicle_GunBoat),
            QGVAR(Invaders_Vehicle_LightHeli),
            QGVAR(Invaders_Vehicle_LightAttackHeli),
            QGVAR(Invaders_Vehicle_AttackHeli),
            QGVAR(Invaders_Vehicle_TransportHeli),
            QGVAR(Invaders_Vehicle_CASPlane),
            QGVAR(Invaders_Vehicle_AAPlane),
            QGVAR(Invaders_Vehicle_TransportPlane),
            QGVAR(Invaders_Vehicle_StaticMG),
            QGVAR(Invaders_Vehicle_StaticAT),
            QGVAR(Invaders_Vehicle_StaticAA),
            QGVAR(Invaders_Vehicle_Mortar),

            // rival units
            QGVAR(Rivals_Base),
            QGVAR(Rivals_Partisan),
            QGVAR(Rivals_Mercenary),
            QGVAR(Rivals_Minuteman),
            QGVAR(Rivals_Enforcer),
            QGVAR(Rivals_CellLeader),
            QGVAR(Rivals_Commander),
            QGVAR(Rivals_Medic),
            QGVAR(Rivals_ExplosivesExpert),
            QGVAR(Rivals_Saboteur),
            QGVAR(Rivals_SpecialistAT),
            QGVAR(Rivals_SpecialistAA),
            QGVAR(Rivals_Oppressor),
            QGVAR(Rivals_Sharpshooter),
            QGVAR(Rivals_Crew),
            QGVAR(Rivals_Pilot),
            QGVAR(Rivals_Unarmed),

            // rival vehicles
            QGVAR(Rivals_Vehicle_LightUnarmed),
            QGVAR(Rivals_Vehicle_LightArmed),
            QGVAR(Rivals_Vehicle_Truck),
            QGVAR(Rivals_Vehicle_APC),
            QGVAR(Rivals_Vehicle_Tank),
            QGVAR(Rivals_Vehicle_Heli),
            QGVAR(Rivals_Vehicle_StaticWpn),
            QGVAR(Rivals_Vehicle_Mortar),

            // civilian units
            QGVAR(Civilians_Base),
            QGVAR(Civilians_Man),
            QGVAR(Civilians_Press),
            QGVAR(Civilians_Worker),

            // civilian vehicles
            QGVAR(Civilians_Vehicle_Car),
            QGVAR(Civilians_Vehicle_Industrial),
            QGVAR(Civilians_Vehicle_Repair),
            QGVAR(Civilians_Vehicle_Medical),
            QGVAR(Civilians_Vehicle_Boat),

            // base modules
            QGVAR(Module_Base),
            QGVAR(Module_Support_Base),

            // occupant support modules
            QGVAR(Module_Support_Occupants_Airstrike),
            QGVAR(Module_Support_Occupants_ASF),
            QGVAR(Module_Support_Occupants_CAS),
            QGVAR(Module_Support_Occupants_CASDive),
            QGVAR(Module_Support_Occupants_CarpetBomb),
            QGVAR(Module_Support_Occupants_Gunship),
            QGVAR(Module_Support_Occupants_Artillery),
            QGVAR(Module_Support_Occupants_Mortar),
            QGVAR(Module_Support_Occupants_Howitzer),
            QGVAR(Module_Support_Occupants_SAM),
            QGVAR(Module_Support_Occupants_CruiseMissile),
            QGVAR(Module_Support_Occupants_QRFLand),
            QGVAR(Module_Support_Occupants_QRFAir),
            QGVAR(Module_Support_Occupants_QRFVehAirdrop),
            QGVAR(Module_Support_Occupants_QRFOrbital),
            QGVAR(Module_Support_Occupants_OrbitalStrike),
            QGVAR(Module_Support_Occupants_UAV),
            QGVAR(Module_Support_Occupants_UAVAttack),
            QGVAR(Module_Support_Occupants_Tank),

            // invader support modules
            QGVAR(Module_Support_Invaders_Airstrike),
            QGVAR(Module_Support_Invaders_ASF),
            QGVAR(Module_Support_Invaders_CAS),
            QGVAR(Module_Support_Invaders_CASDive),
            QGVAR(Module_Support_Invaders_CarpetBomb),
            QGVAR(Module_Support_Invaders_Gunship),
            QGVAR(Module_Support_Invaders_Artillery),
            QGVAR(Module_Support_Invaders_Mortar),
            QGVAR(Module_Support_Invaders_Howitzer),
            QGVAR(Module_Support_Invaders_SAM),
            QGVAR(Module_Support_Invaders_CruiseMissile),
            QGVAR(Module_Support_Invaders_QRFLand),
            QGVAR(Module_Support_Invaders_QRFAir),
            QGVAR(Module_Support_Invaders_QRFVehAirdrop),
            QGVAR(Module_Support_Invaders_QRFOrbital),
            QGVAR(Module_Support_Invaders_OrbitalStrike),
            QGVAR(Module_Support_Invaders_UAV),
            QGVAR(Module_Support_Invaders_UAVAttack),
            QGVAR(Module_Support_Invaders_Tank),

            // misc modules
            QGVAR(Module_Misc_Base),
            QGVAR(Module_Misc_AddToHC),
        };
        weapons[] = {};
        requiredVersion = REQUIRED_VERSION;
        requiredAddons[] = {"A3A_Core", "A3_Characters_F"};
        author = AUTHOR;
        authors[] = { AUTHORS };
        authorUrl = "";
        VERSION_CONFIG;
    };
};

class CBA_Extended_EventHandlers_base; // Needed for CfgVehicles.hpp

#include "cfgFactionClasses.hpp"
#include "cfgEditorSubcategories.hpp"
#include "cfgVehicles.hpp"
#include "cfgGroups.hpp"
#include "cfgFunctions.hpp"
