class vehicles_contact : vehicles_base
{
    ITEM(I_UGV_02_Science_F, 8000, "UAV", VEHICLE_CONDITION_UAV);
    ITEM(I_UGV_02_Demining_F, 9500, "UAV", VEHICLE_CONDITION_UAV);
    ITEM(C_Tractor_01_F, 550, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(I_E_Offroad_01_covered_F, 1120, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(I_E_Offroad_01_comms_F, 1120, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
};
