class vehicles_apex : vehicles_base
{
    ITEM(B_LSV_01_AT_F, 21200, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(B_LSV_01_armed_F, 8400, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(O_LSV_02_AT_F, 13000, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(O_LSV_02_armed_F, 6000, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(I_C_Offroad_02_AT_F, 6100, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(I_C_Offroad_02_LMG_F, 2100, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(I_C_Boat_Transport_02_F, 2200, "BOAT", VEHICLE_CONDITION_BOAT);
    ITEM(C_Scooter_Transport_01_F, 1100, "BOAT", VEHICLE_CONDITION_BOAT);
    ITEM(B_T_VTOL_01_armed_F, 84000, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(B_T_VTOL_01_infantry_F, 75700, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(B_T_VTOL_01_vehicle_F, 65500, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(O_T_VTOL_02_infantry_dynamicLoadout_F, 93500, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(O_T_VTOL_02_vehicle_dynamicLoadout_F, 89300, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(I_C_Plane_Civil_01_F, 11600, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(B_T_UAV_03_dynamicLoadout_F, 23350, "UAV", VEHICLE_CONDITION_UAV);
    ITEM(O_T_UAV_04_CAS_F, 18100, "UAV", VEHICLE_CONDITION_UAV);
    ITEM(B_CTRG_LSV_01_light_F, 1250, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(B_LSV_01_unarmed_F, 1250, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(O_LSV_02_unarmed_F, 1250, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(I_C_Offroad_02_unarmed_F, 960, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
};
