
class vehicles_tanks : vehicles_base
{
    ITEM(I_LT_01_AA_F, 21000, "AA", VEHICLE_CONDITION_AA);
    ITEM(I_LT_01_scout_F, 3000, "AA", VEHICLE_CONDITION_AA);
    ITEM(I_LT_01_cannon_F, 18500, "APC", VEHICLE_CONDITION_APC);
    ITEM(I_LT_01_AT_F, 23750, "APC", VEHICLE_CONDITION_APC);
    ITEM(O_MBT_04_cannon_F, 67180, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(O_MBT_04_command_F, 72460, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(B_AFV_Wheeled_01_cannon_F, 45220, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(B_AFV_Wheeled_01_up_cannon_F, 61180, "TANK", VEHICLE_CONDITION_TANK);
};
    
