class vehicles_scifivp : vehicles_base
{
    ITEM(TKE_Ext_Bearcat_AA, 12500, "AA", VEHICLE_CONDITION_AA);
    ITEM(TKE_Ext_Bearcat_Unarmed, 5700, "APC", VEHICLE_CONDITION_APC);
    ITEM(TKE_Ext_Bearcat_Autocannon, 23950, "APC", VEHICLE_CONDITION_APC);
    ITEM(TKE_Ext_Dragonfly_A, 42360, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(TKE_Ext_Dragonfly_S, 42360, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(TKE_Ext_GUSA, 105900, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(TKE_Ext_GUSM, 85100, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(TKE_Ext_Bearcat_Cannon, 45220, "TANK", VEHICLE_CONDITION_TANK);
};
