class vehicles_spex : vehicles_base
{
    ITEM(SPEX_CW_Humber_MkII, 9100, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(SPEX_CW_Humber_LRC, 3100, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(SPEX_CW_Humber_MkIV, 14100, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(SPEX_CW_Humber_MkIV_PLM, 14100, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(SPEX_LCVP, 5250, "BOAT", VEHICLE_CONDITION_BOAT);
    ITEM(SPEX_HORSA, 13100, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(SPEX_HORSA_MK2, 8300, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(SPEX_C47_Skytrain, 16600, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(SPEX_CG4_WACO, 9500, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(SPEX_GC4_WACO_Cargo, 5600, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(SPEX_M2_60, 6000, "STATICMORTAR", VEHICLE_CONDITION_STATICMORTAR);
    ITEM(SPEX_CW_Cromwell_Mk5, 33100, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(SPEX_CW_Cromwell_Mk6, 36400, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(SPEX_CW_Sherman_Vc, 40200, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(SPEX_T3_Trailer, 612, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(SPEX_T3_Trailer_Ammo, 7250, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(SPEX_T3_Trailer_Fuel, 7250, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(SPEX_T3_Trailer_Repair, 7250, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(SPEX_CW_Bedford_MWD, 1450, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
};
