class vehicles_jets : vehicles_base
{
    ITEM(B_Ship_Gun_01_F, 66000, "ARTILLERY", VEHICLE_CONDITION_ARTILLERY);
    ITEM(B_Ship_MRLS_01_F, 309375, "ARTILLERY", VEHICLE_CONDITION_ARTILLERY);
    ITEM(B_Plane_Fighter_01_F, 97800, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(B_Plane_Fighter_01_Stealth_F, 85050, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(O_Plane_Fighter_02_F, 97000, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(O_Plane_Fighter_02_Stealth_F, 97000, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(I_Plane_Fighter_04_F, 57300, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(B_AAA_System_01_F, 40000, "STATICAA", VEHICLE_CONDITION_STATICAA);
    ITEM(B_SAM_System_01_F, 50000, "STATICAA", VEHICLE_CONDITION_STATICAA);
    ITEM(B_SAM_System_02_F, 60000, "STATICAA", VEHICLE_CONDITION_STATICAA);
    ITEM(B_SAM_System_03_F, 30000, "STATICAA", VEHICLE_CONDITION_STATICAA);
    ITEM(B_Radar_System_01_F, 30000, "STATICAA", VEHICLE_CONDITION_STATICAA);
    ITEM(O_SAM_System_04_F, 30000, "STATICAA", VEHICLE_CONDITION_STATICAA);
    ITEM(O_Radar_System_02_F, 30000, "STATICAA", VEHICLE_CONDITION_STATICAA);
    ITEM(B_UAV_05_F, 19400, "UAV", VEHICLE_CONDITION_UAV);
};
